apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-pdl-pilot
  namespace: default
  labels:
    team: teamcrm
spec:
  webproxy: false
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 2048Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/sbs/sf-pdl-pilot/default
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvsfpdl
      - mountPath: /var/run/secrets/nais.io/apigw/security-token-service-token
        kvPath: /apikey/apigw/dev/security-token-service-token/sf-pdl_q1
      - mountPath: /var/run/secrets/nais.io/apigw/pdl-api
        kvPath: /apikey/apigw/dev/pdl-api/sf-pdl_q2
  env:
    - name: KAFKA_BROKERS
      value: SASL_SSL://b27apvl00045.preprod.local:8443,SASL_SSL://b27apvl00046.preprod.local:8443,SASL_SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_CLIENTID
      value: sf-pdl-pilot-v1
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: KAFKA_TOPIC_SF
      value: privat-sf-person-pilot-v1
    - name: PDL_GRAPHQL_URL
      value: 'https://api-gw-q2.oera.no/pdl-api/graphql'
    - name: STS_REST_URL
      value: 'https://api-gw-q1.oera.no/security-token-service/rest/v1/sts/token'
    - name: MS_BETWEEN_WORK
      value: '600000'