apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-pdl-pilot
  namespace: default
  labels:
    team: teamcrm
spec:
  webproxy: true
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 2048Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/sbs/sf-pdl-pilot/default
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/prod/srvsfpdl
      - mountPath: /var/run/secrets/nais.io/apigw/security-token-service-token
        kvPath: /apikey/apigw/prod/security-token-service-token/sf-pdl
      - mountPath: /var/run/secrets/nais.io/apigw/pdl-api
        kvPath: /apikey/apigw/prod/pdl-api/sf-pdl
  env:
    - name: KAFKA_BROKERS
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00148.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443,SASL_SSL://a01apvl00150.adeo.no:8443
    - name: KAFKA_CLIENTID
      value: sf-pdl-pilot-v1
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: KAFKA_TOPIC_SF
      value: privat-sf-person-pilot-v1
    - name: PDL_GRAPHQL_URL
      value: 'https://api-gw.oera.no/pdl-api/graphql'
    - name: STS_REST_URL
      value: 'https://api-gw.oera.no/security-token-service/rest/v1/sts/token'
    - name: MS_BETWEEN_WORK
      value: '3200000'
    - name: SF_INSTTYPE
      value: 'PRODUCTION'
    - name: SF_VERSION
      value: 'v48.0'
